#!/bin/bash

BACKUPDIR=/Volumes/Archive/backup
SCRIPTDIR=/Users/martind/git/link-backup

ls $BACKUPDIR &> /dev/null
if [ $? -ne 0 ]; then
	echo "Archive drive not connected"
	echo "connect drive to run this backup"
	exit 1
fi

python $SCRIPTDIR/link_backup.py -d ~/Documents -b $BACKUPDIR/documents_backup
python $SCRIPTDIR/link_backup.py -d ~/Movies -b $BACKUPDIR/movies_backup
python $SCRIPTDIR/link_backup.py -d ~/Pictures -b $BACKUPDIR/pictures_backup
python $SCRIPTDIR/link_backup.py -d ~/Virtual\ Machines -b $BACKUPDIR/vm_backup
python $SCRIPTDIR/link_backup.py -d ~/VirtualBox\ VMs -b $BACKUPDIR/vbox_backup
python $SCRIPTDIR/link_backup.py -d ~/books -b $BACKUPDIR/books_backup
python $SCRIPTDIR/link_backup.py -d ~/docker -b $BACKUPDIR/docker_backup
python $SCRIPTDIR/link_backup.py -d ~/finances -b $BACKUPDIR/finances_backup
python $SCRIPTDIR/link_backup.py -d ~/games -b $BACKUPDIR/games_backup
python $SCRIPTDIR/link_backup.py -d ~/resumes -b $BACKUPDIR/resumes_backup
python $SCRIPTDIR/link_backup.py -d ~/travel -b $BACKUPDIR/travel_backup
python $SCRIPTDIR/link_backup.py -d ~/work -b $BACKUPDIR/work_backup
python $SCRIPTDIR/link_backup.py -d ~/apartments -b $BACKUPDIR/apartments_backup
python $SCRIPTDIR/link_backup.py -d ~/exercism -b $BACKUPDIR/exercism_backup
python $SCRIPTDIR/link_backup.py -d ~/images -b $BACKUPDIR/images_backup
python $SCRIPTDIR/link_backup.py -d ~/linuxacademy -b $BACKUPDIR/linuxacademy_backup
python $SCRIPTDIR/link_backup.py -d ~/git -b $BACKUPDIR/git_local_backup
python $SCRIPTDIR/link_backup.py -d ~/notes -b $BACKUPDIR/notes_backup
python $SCRIPTDIR/link_backup.py -d ~/bible-study -b $BACKUPDIR/bible-study_backup
python $SCRIPTDIR/link_backup.py -d /Applications -b $BACKUPDIR/applications_backup
python $SCRIPTDIR/link_backup.py -d ~/Pictures -b $BACKUPDIR/pictures_backup

