# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-standards:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9.7
        architecture: x64 
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: python-build
      run: |
        # install needed package
        pip install wheel
        
        # build package
        python setup.py sdist bdist_wheel bdist_egg

    - name: get-version
      run: |
        VERSION=$(grep version setup.py | cut -d "'" -f 2)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.API_TOKEN }}
        file: dist/*
        tag: ${{ env.VERSION }}
        overwrite: true
        body: "${{ env.VERSION }} release of link-backup from GitHub Actions"
        file_glob: true
